name: softales
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  flutter_secure_storage: ^6.0.0  
  image_picker: ^0.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.20.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inika
      fonts:
        - asset: assets/fonts/Inika-Bold.ttf
        - asset: assets/fonts/Inika-Regular.ttf
    - family: Inder
      fonts:
        - asset: assets/fonts/Inder-Regular.ttf